version: '3.8'

services:
  app:
    build: .
    container_name: event_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=eventdb
    volumes:
      - .:/var/www/EventManagementSystem

  db:
    image: mysql:latest
    container_name: event_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventdb
    volumes:
      - db_data:/var/lib/mysql
      - ./datadump.sql:/docker-entrypoint-initdb.d/datadump.sql

volumes:
  db_data:
